# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  publish_artifact:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Zip
      run: |
        zip -r 005-rockpaperscissorsboom.zip ${{ github.workspace }}/Code

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        # Artifact name
        name: 005-rockpaperscissorsboom
        # A file, directory or wildcard pattern that describes what to upload
        path: ${{ github.workspace }}/Code
        retention-days: 3
