name: WTH RPSB - Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  Build-Image:

    runs-on: ubuntu-latest
    env:
      imageName: 'rockpaperscisors-server'
      imageDockerFile: 'Dockerfile-Server'

    steps:
    - uses: actions/checkout@v2

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v1.1.1
      
    - name: Docker Login
      uses: docker/login-action@v1.8.0
      with:
        username: ${{ secrets.WTH_REGISTRY_UNAME }}
        password: ${{ secrets.WTH_REGISTRY_UPASS }}
        registry: ${{ secrets.WTH_REGISTRY }}
        
    - name: Build and push Docker images
      uses: docker/build-push-action@v2.2.1
      with:
        context: ./Code
        file: ./${{ env.imageDockerFile }}
        push: true
        tags: ${{ secrets.WTH_REGISTRY }}/${{ env.imageName }}:$(date +%s)
