name: WTH RPSB - Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  Build-Image:

    runs-on: ubuntu-latest

    outputs:
      image: ${{ steps.image-name.outputs.image }}

    env:
      registry: rvlabs.azurecr.io
      imageName: 'rockpaperscisors-server'
      imageDockerFile: 'Dockerfile-Server'

    steps:
    - uses: actions/checkout@v2

    - name: Image Tag
      id: image-tag
      run: |
        echo "::set-output name=tag::$(date +%s)"

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v1.1.1
      
    - name: Docker Login
      uses: docker/login-action@v1.8.0
      with:
        username: ${{ secrets.WTH_REGISTRY_UNAME }}
        password: ${{ secrets.WTH_REGISTRY_UPASS }}
        registry: ${{ env.registry }}
        
    - name: Build and push image
      uses: docker/build-push-action@v2.2.1
      with:
        context: ./Code
        file: ./Code/${{ env.imageDockerFile }}
        push: true
        tags: ${{ env.registry }}/${{ env.imageName }}:${{ steps.image-tag.outputs.tag }}

    - name: Set Image to Deploy
      id: image-name
      run: |
        echo "::set-output name=image::${{ env.imageName }}:${{ steps.image-tag.outputs.tag }}"
      

  Deploy-Image:

    runs-on: ubuntu-latest
    needs: [Build-Image]
    env:
      imageName: ${{ needs.Build-Image.outputs.image }}
      webApp: wth-rpsb-app-7603
      registry: rvlabs.azurecr.io

    steps:
      - name: echo
        run: |
          echo "needs:  ${{ needs.Build-Image.outputs.image }}"
          echo "env: ${{ env.imageName }}"

      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
          username: ${{ secrets.WTH_REGISTRY_UNAME }}
          password: ${{ secrets.WTH_REGISTRY_UPASS }}
          login-server: ${{ env.registry }}

      - name: Azure WebApp
        uses: Azure/webapps-deploy@v2
        with:
          app-name: ${{ env.webApp }} 
          publish-profile: ${{ secrets.WTH_WEBAPP_SITECRED }}
          images: ${{ needs.Build-Image.outputs.image }}

